### ISSUE TITLE
Unable to start the project

### ISSUE THREAD

**Issue by husky-zack** [City-of-Helsinki/varaamo#1252]
### Issue
Upon running `docker compose up` the process throws following error 

`/usr/src/app/server/config.js:1`
`import path from 'path';`
`SyntaxError: Cannot use import statement outside a module`

### Steps to Reproduce
1. Checkout master 
2. Run  `docker compose up`

### What we tried
Added `"type" : "module"` to package.json, but that only caused new round of errors.

### Additional Information
I participated in a hackathon past weekend with the theme how to better utilise spaces owned by city of Zagreb. Me and my team loved your projects (both Respa and Varaamo). In our opinion, your projects would solve almost all requirements that hackathon had. We managed to get Respa running, but unfortunately not Varaamo and couldn't present your solution to the fullest. 
Non the less, kudos to your team on a great open source addition.

**Comment by vergama** [comment]
This repo is deprecated; see instead https://github.com/City-of-Helsinki/tilavarauspalvelu-ui for the React.js frontend on the new City of Helsinki space/resource reservation system.
