### ISSUE TITLE
Group admin resources by purpose

### ISSUE THREAD

**Issue by lraivio** [City-of-Helsinki/varaamo#563]
![omat_tilat_kategoriat](https://cloud.githubusercontent.com/assets/946697/24392728/c830004a-139d-11e7-92b5-9a2b3edc2075.png)

**Comment by YoYuUm** [comment]
Use only purposes that don't have a parent (Main purposes)

**Comment by lraivio** [comment]
Needs changes in the backend before the feature can be finished.
