### ISSUE TITLE
Date picker is not displayed properly on IE11

### ISSUE THREAD

**Issue by lraivio** [City-of-Helsinki/varaamo#573]
- [x] The calendar shows only 4 days per week.
- [x] The current date marker is not vertically aligned.

![ie-date-picker-bug](https://cloud.githubusercontent.com/assets/946697/24742016/048a3c12-1ab1-11e7-973d-b9374c545646.png)

**Comment by YoYuUm** [comment]
The reason why this is happening seems to be a bug with flexbox in IE11. In this case the container has the property `display: inline-flex` and `min-width: 100%`
