### ISSUE TITLE
Show search page resources on a map

### ISSUE THREAD

**Issue by lraivio** [City-of-Helsinki/varaamo#617]
Tasks in this issue:
- [x] Display a map
- [x] Show search results as markers on the map
- [x] Add a toggle to switch between the map view and search results

The location can be found from unit data. The resources have a location field as well, but it seems to be null most of the time.

This issue is only for making the "mvp" version of the map.
Styling and more advanced functionality will be done in later issues. 
Now the map can be behind a toggle. Later it will be shown at the same time with the results listing so this should be kept in mind when implementing the Map container.
Below are the current designs on how the search results would look in the end with the map and new Helsinki brand:

Map closed:

<img width="382" alt="varaamo2-lista" src="https://cloud.githubusercontent.com/assets/946697/25957615/6ea9e2e6-3677-11e7-9a3c-1ac0a3e8d6a1.png">

Map open:

<img width="382" alt="varaamo2-kartta" src="https://cloud.githubusercontent.com/assets/946697/25957595/669a0a2c-3677-11e7-9a0d-fd12801c7a6c.png">

**Comment by YoYuUm** [comment]
Image links are broken

**Comment by lraivio** [comment]
Updated the images
