### ISSUE TITLE
Number of resources in a unit should always be visible beside map markers

### ISSUE THREAD

**Issue by lraivio** [City-of-Helsinki/varaamo#666]
Now the number of resources in a unit matching the search is only visible when hovering the markers.

**Comment by YoYuUm** [comment]
@lraivio So do you think this should always show the number of resources in the unit with the same pop-out that it is shown at the moment? I think there's going to be plenty of overlaps, but perhaps it's fine. Have you though about some different styles for the popup?

**Comment by lraivio** [comment]
@YoYuUm This was in Sami's design so maybe something like this:

![image](https://user-images.githubusercontent.com/946697/27541673-74b1bb7a-5a8d-11e7-8b5b-41854d00fe78.png)

**Comment by lraivio** [comment]
Closed in #706.
