### ISSUE TITLE
AdminResources view not completely visible in destop

### ISSUE THREAD

**Issue by YoYuUm** [City-of-Helsinki/varaamo#735]
In desktop you can't hide the navbar, some AdminResources content stays behind the Navbar:

<img width="1678" alt="screen shot 2017-08-03 at 13 50 54" src="https://user-images.githubusercontent.com/2705679/28918648-d75199ca-7852-11e7-9b37-bda7c78621b6.png">

**Comment by YoYuUm** [comment]
Modals have the same issue:
<img width="1264" alt="screen shot 2017-08-07 at 13 27 43" src="https://user-images.githubusercontent.com/2705679/29022993-4e71c254-7b74-11e7-8e36-0970867698c5.png">

**Comment by lraivio** [comment]
Closed in #740.
