### ISSUE TITLE
The modals still contain the Helsinki logo even with Espoo customizations.

### ISSUE THREAD

**Issue by YoYuUm** [City-of-Helsinki/varaamo#764]
The modals still contain the Helsinki logo even with Espoo customizations. Issue with changing this is that the modal is outside of the <app> div in html and thus won't be affected by the espoo customizations since the espoo classname is added to the app div. A quick fix could be to use the logo component in all the modals with new styles or somehow move the modal inside the app or the espoo classname upper in hierarchy. Maybe you'll come up with a good solution. If it seems that this would take super long time to implement, then a secondary option is to just get rid of the helsinki logo in the modals altogether.

**Comment by lraivio** [comment]
Closed in #775.
