### ISSUE TITLE
Test espoo changes

### ISSUE THREAD

**Issue by YoYuUm** [City-of-Helsinki/varaamo#772]
Test that all the changes work nicely together and test quickly IE, Edge and on some mobile devices

**Comment by YoYuUm** [comment]
- [ ] Espoo logo does not appear in side navbar (Helsinki logo appears instead)
- [ ] Modal background color is not the same than Espoo brand color.

**Comment by YoYuUm** [comment]
IE10:
- [ ] Logo is not centered in modal
![screen shot 2017-12-21 at 18 56 23](https://user-images.githubusercontent.com/2705679/34266154-e1646162-e680-11e7-8e59-1cd77ba96b74.png)

**Comment by lraivio** [comment]
At least for me the correct logos appear in the navbar.
IE 10 we no longer need to support.
